const decadeData = [
     {
          player : {
               name : "Lebron James",
               team : "LOS ANGESLES LAKERS",
               bio : "LeBron James took hold of the 2010s and never let go. He’s easily the most consistent player of the decade, if not of all time. With his unique combination of size, athleticism and court vision, he became a four-time NBA MVP. After leading the Miami Heat to titles in 2012 and 2013, James returned to Cleveland and helped the franchise claim its first championship in 2016, being the first to comeback from a 3-1 deficit",
               img : "https://firebasestorage.googleapis.com/v0/b/statsiege.appspot.com/o/decadePlayers%2Flebron.jpg?alt=media&token=68e4ec72-e139-4223-991c-10a8ec4bee3d",
               wikipedia : "https://en.wikipedia.org/wiki/LeBron_James",
               teamLink : "http://localhost:3000/dashboard/1610612747",
               ppg : "27.1",
               apg : "7.3",
               rpg : "7.4",
               mvp : ["4x", "2009, 2010, 2012, 2013"],
               scoring : null,
               allNba : ["10x", "2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018"],
               championship : ["3x", "2012, 2013, 2016"],
               color : ["#44086C", "#FFE300"]
          },
          style : 'width: 400px; height: 600px; margin-left: 30vw;',
          tabletStyle : ' width: 550px; height: 750px; margin-left: 25vw;',
          desktopStyle : 'margin-left: 260px;',
     },
     {
          player : {
               name : "Stephen Curry",
               team : "GOLDEN STATE WARRIORS",
               img : "https://firebasestorage.googleapis.com/v0/b/statsiege.appspot.com/o/decadePlayers%2Fcurry.jpeg?alt=media&token=f9c5f6f1-e3a1-4dd4-a5af-b276b53eccad",
               bio : "Steph single-handedly changed the trajectory of basketball, revolutionizing the way the game is played with his three-point accuracy. Curry maintained a 48/44/91 shooting % for the entire decade. Which translated into a two time MVP award and the first unanimous MVP. Curry has also been the catalyst for the most dominant modern NBA dynasty, leading the Golden State Warriors to a league-record 73-win season, and three-championships.",
               wikipedia : "https://en.wikipedia.org/wiki/Stephen_Curry",
               teamLink : "http://localhost:3000/dashboard/1610612744",
               ppg : "23.5",
               apg : "6.6",
               rpg : "4.5",
               mvp : ["2x", "2015, 2016"],
               allNba : ["3x", "2015, 2016, 2019"],
               scoring : ["1x","2016"],
               championship : ["3x", "2015, 2017, 2018"],
               color : ["#1D428A","#FFC72C"]
          },
          style : 'width: 530px; height: 750px; margin-left: 35vw; padding-bottom: 100px;',
          tabletStyle : 'width: 630px; height: 850px; margin-left: 33vw; padding-bottom: 100px;',
          laptopStyle : 'margin-left: 25vw;',
          desktopStyle : 'margin-left: 360px;',
     },
     {
          player : {
               name : "James Harden",
               team : "Houston Rockets",
               bio : "Although he was drafted No. 3 overall in the 2009 NBA Draft, James Harden's game has made a quantum leap since his rookie season, the first year of this decade, when he averaged 10 points, three rebounds and two assists per game. By the end of the decade, Harden was doing things on offense no player since Michael Jordan had done, averaging 36.1 points per game in 2018-19.  Over his final seven seasons of the decade, he averaged 29.0 points, 7.7 assists, 6.0 rebounds and 3.1 triples. By restricting his offense to the analytics diet of threes, layups and free throws, the Beard became as potent a point-producer as this decade witnessed.",
               img : "https://firebasestorage.googleapis.com/v0/b/statsiege.appspot.com/o/decadePlayers%2Fharden.jpg?alt=media&token=b794229f-d124-4403-8204-29b2dcd2ecd3",
               wikipedia : "https://en.wikipedia.org/wiki/James_Harden",
               teamLink : "http://localhost:3000/dashboard/1610612745",
               ppg : "24.3",
               apg : "6.2",
               rpg : "5.2",
               mvp : ["1x", "2018"],
               allNba : ["5x", "2014, 2015, 2017, 2018, 2019"],
               scoring : ["2x", "2018, 2019"],
               championship : null,
               color : ["#000000","#CE1141"]
          },
          style : 'width:650px; height: 650px; margin-left: 13vw;',
          tabletStyle : 'width: 900px; height: 730px; margin-left: 23vw;',
          desktopStyle : 'width: 1000px; height: 800px; margin-left: 280px;',
     },
     {
          player : {
               name : "Russell Westbrook",
               team : "Houston Rockets",
               bio : "Russell Westbrook was a perennial All-NBA performer while playing with Kevin Durant and James Harden and an MVP player on his own. He finished off the decade by breaking Oscar Robertson's triple-double records and averaging a triple-double for three straight seasons. He won MVP one of those, won two scoring titles and two assist titles, selected All-NBA eight times, twice earning the first-team distinction and made four Conference Finals and one Finals. He'll forever be a divisive player because of his visible shortcomings, but his consistent night-to-night effort and performance still helped steer OKC to the decade's second-most victories. ",
               img : "https://firebasestorage.googleapis.com/v0/b/statsiege.appspot.com/o/decadePlayers%2Fwestbrook.jpg?alt=media&token=6d6a9e41-8496-4212-bff0-87233d3ba78f",
               wikipedia : "https://en.wikipedia.org/wiki/Russell_Westbrook",
               teamLink : "http://localhost:3000/dashboard/1610612745",
               ppg : "23.0",
               apg : "8.4",
               rpg : "7.0",
               mvp : ["1x", "2017"],
               allNba : ["2x", "2016, 2017"],
               scoring : ["2x","2015, 2017"],
               championship : null,
               color : ["#000000","#CE1141"]
          },
          style : 'width: 550px; height: 850px; margin-left: 45vw;',
          tabletStyle : 'width: 650px; height: 950px; margin-left: 37vw;',
          laptopStyle : 'margin-left: 32vw;',
          desktopStyle : 'width: 650px; height: 950px; margin-left: 350px;',
     },
     {
          player : {
               name : "Kevin Durant",
               team : "Brooklyn Nets",
               bio : "It’s easy to forget now, but Durant finished top two in MVP voting four of the first five years this decade. This seven-footer just scored 27 points a game on 50/38/89 shooting for an entire decade. He won an MVP with the Thunder, then joined the Warriors for two titles they may not have won without him, winning both Finals MVPs. Do you realize KD has made the Conference Finals in seven of his last eight playoff appearances? Durant left a weird taste in our mouths finishing off the decade, but he’s become an all timer before our eyes.",
               img : "https://firebasestorage.googleapis.com/v0/b/statsiege.appspot.com/o/decadePlayers%2Fdurant.png?alt=media&token=70c8768d-52d8-404c-be1c-0d28268890c8",
               wikipedia : "https://en.wikipedia.org/wiki/Kevin_Durant",
               teamLink : "http://localhost:3000/dashboard/1610612751",
               ppg : "27.0",
               apg : "4.1",
               rpg : "7.1",
               mvp : ["1x", "2017"],
               allNba : ["6x", "2010, 2011, 2013, 2014, 2018"],
               scoring : ["4x","2010, 2011, 2012, 2014"],
               championship : ["2x", "2017, 2018"],
               color : ["#000000","#777D84"]
          },
          style : 'width: 530px; height: 650px; margin-left: 45vw;',
          tabletStyle : 'width: 630px; height: 680px; margin-left: 33vw;',
          laptopStyle : 'margin-left: 25vw;',
          desktopStyle : 'margin-left: 360px;',
     }
]

export default decadeData;